---
- hosts: k8snodes
  remote_user: root
  become: no
  #become_user: root
  #become_method: sudo
  tasks:
    - name: push authorized_keys
      authorized_key: 
        user: root
        #key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"  需要填写本地主机的公钥路径
        key: "{{ lookup('file', '/home/admin/.ssh/id_rsa.pub') }}"
        state: present
        exclusive: yes