---
- hosts: k8snodes
  remote_user: root
  become: no
  #become_user: root
  #become_method: sudo
  #gather_facts: false
  tasks:
    - name: run_shell_script
      script: /home/admin/gitcode/test.sh
      args:
        chdir: /tmp
